import React, { useEffect, useMemo, useState } from 'react';
import { Activity, ArrowDownRight, ArrowUpRight, Bell, BookOpen, CalendarDays, Check, ChevronDown, ChevronRight, CircleHelp, Clock3, Compass, Flame, Flower2, Heart, Home, ImagePlus, Leaf, LogOut, Menu, MessageCircle, MoreHorizontal, Plus, Search, Settings2, Sparkles, Target, Trophy, Users, X } from 'lucide-react';
import { calculateStreak, cleanText, dateKey, progressPercent, safeRead, safeWrite, validEmail, validPassword, validateSession } from './logic.js';
import { addCloudComment, deleteCloudComment, deleteCloudPost, saveCloudData, setCloudLike, uploadPostImage } from './firebase.js';

const starter = {
 user:{name:'Maya Chen',email:'maya@example.com',username:'mayamakes',bio:'Learning out loud, one small step at a time.'},
 skills:[{id:'s1',name:'Watercolor',category:'Art & design',level:'Beginner',color:'peach',icon:'🎨',goal:12},{id:'s2',name:'Guitar',category:'Music',level:'Intermediate',color:'lavender',icon:'🎸',goal:20},{id:'s3',name:'Japanese',category:'Languages',level:'Beginner',color:'mint',icon:'🌱',goal:15}],
 sessions:[{id:'l1',skillId:'s1',minutes:35,activity:'Loose florals in my sketchbook',practicedAt:new Date().toISOString()},{id:'l2',skillId:'s2',minutes:45,activity:'Practiced chord transitions',practicedAt:new Date(Date.now()-86400000).toISOString()},{id:'l3',skillId:'s3',minutes:25,activity:'Learned 12 new words',practicedAt:new Date(Date.now()-2*86400000).toISOString()},{id:'l4',skillId:'s1',minutes:40,activity:'Color mixing practice',practicedAt:new Date(Date.now()-4*86400000).toISOString()}],
 goals:[{id:'g1',skillId:'s1',title:'Finish my first floral study',target:12,unit:'hours',deadline:'2026-10-31',status:'In progress'},{id:'g2',skillId:'s2',title:'Play a song all the way through',target:20,unit:'sessions',deadline:'2026-11-15',status:'In progress'}],
 posts:[{id:'p1',author:'Aisha Patel',handle:'aishasketches',avatar:'AP',color:'lavender',skill:'Watercolor',time:'2 hours ago',text:'A little reminder that progress can be quiet. Finally getting the hang of wet-on-wet blooms 🌷',likes:18,liked:false,comments:[{name:'Maya',text:'These colors are so lovely!'}]},{id:'p2',author:'Leo Martin',handle:'leomakesmusic',avatar:'LM',color:'mint',skill:'Guitar',time:'Yesterday',text:'Day 14 of showing up for my guitar practice, even when it’s just 10 minutes. It adds up 🎸',likes:12,liked:false,comments:[]}]
};
const STORE='skillbloom-v1';
function loadDemo(){const saved=safeRead(STORE);if(!saved||typeof saved!=='object'||!saved.user||!Array.isArray(saved.skills)||!Array.isArray(saved.sessions)||!Array.isArray(saved.goals)||!Array.isArray(saved.posts))return starter;const validUser=['name','email','username','bio'].every(k=>typeof saved.user[k]==='string');const validSkills=saved.skills.every(s=>s&&typeof s.id==='string'&&typeof s.name==='string'&&typeof s.goal==='number');const validSessions=saved.sessions.every(s=>s&&typeof s.id==='string'&&typeof s.skillId==='string'&&Number.isFinite(Number(s.minutes))&&typeof s.practicedAt==='string');const validGoals=saved.goals.every(g=>g&&typeof g.id==='string'&&typeof g.skillId==='string'&&Number.isFinite(Number(g.target)));const validPosts=saved.posts.every(p=>p&&typeof p.id==='string'&&typeof p.author==='string'&&typeof p.text==='string'&&Array.isArray(p.comments));return validUser&&validSkills&&validSessions&&validGoals&&validPosts?saved:starter}
const nav=[['Home',Home],['My skills',Leaf],['Practice log',CalendarDays],['Goals',Target],['Community',Users]];
const initials=n=>cleanText(n,40).split(/\s+/).filter(Boolean).slice(0,2).map(s=>s[0]).join('').toUpperCase()||'SB';
const Avatar=({name,color='peach',small=false})=><span className={`avatar ${color} ${small?'small':''}`}>{initials(name)}</span>;

export default function App({cloudUser=null,cloudError:initialCloudError=''}){
 const [data,setData]=useState(()=>cloudUser?.data||loadDemo()),[page,setPage]=useState('Home'),[modal,setModal]=useState(''),[toast,setToast]=useState(''),[query,setQuery]=useState(''),[mobileNav,setMobileNav]=useState(false),[cloudError,setCloudError]=useState(initialCloudError);
 const [session,setSession]=useState({skillId:'s1',minutes:'30',activity:'',practicedAt:dateKey(new Date())});
 const [skill,setSkill]=useState({name:'',category:'Creative',level:'Beginner',goal:'5'});
 const [postText,setPostText]=useState(''),[postFile,setPostFile]=useState(null),[uploading,setUploading]=useState(false),[openComments,setOpenComments]=useState({}),[commentDrafts,setCommentDrafts]=useState({});
 useEffect(()=>{if(cloudUser){const timer=window.setTimeout(()=>saveCloudData(cloudUser.user,data).then(()=>setCloudError('')).catch(()=>setCloudError('Cloud sync paused. Check your connection and Firestore rules.')),600);return()=>window.clearTimeout(timer)}if(!safeWrite(STORE,data))notify('Your browser storage is full. Export or clear some data.');},[data,cloudUser]);
 function notify(message){setToast(message);window.setTimeout(()=>setToast(''),3200)}
 const me=data.user||starter.user;
 const totalMinutes=data.sessions.reduce((n,s)=>n+(Number(s.minutes)||0),0);
 const streak=calculateStreak(data.sessions);
 const skillMinutes=id=>data.sessions.filter(s=>s.skillId===id).reduce((n,s)=>n+(Number(s.minutes)||0),0);
 const skillWeekMinutes=id=>data.sessions.filter(s=>{const t=new Date(s.practicedAt).getTime();return s.skillId===id&&Number.isFinite(t)&&Date.now()-t<7*86400000&&Date.now()>=t}).reduce((n,s)=>n+(Number(s.minutes)||0),0);
 const goalCurrent=g=>g.unit==='sessions'?data.sessions.filter(s=>s.skillId===g.skillId).length:g.unit==='hours'?skillMinutes(g.skillId)/60:0;
 const setUser=patch=>setData(d=>({...d,user:{...d.user,...patch}}));
 function addSession(e){e.preventDefault();const error=validateSession(session);if(error){notify(error);return}if(!data.skills.some(s=>s.id===session.skillId)){notify('Choose one of your skills first.');return}setData(d=>({...d,sessions:[{...session,id:crypto.randomUUID(),minutes:Number(session.minutes),activity:cleanText(session.activity,100),practicedAt:new Date(session.practicedAt+'T12:00:00').toISOString()},...d.sessions]}));setSession(s=>({...s,activity:''}));notify('Practice saved. Small steps count!')}
 function addSkill(e){e.preventDefault();const name=cleanText(skill.name,48);const goal=Number(skill.goal);if(name.length<2){notify('Skill name needs at least 2 characters.');return}if(data.skills.some(s=>s.name.toLowerCase()===name.toLowerCase())){notify('You already have a skill with that name.');return}if(!Number.isFinite(goal)||goal<1||goal>10000){notify('Set a goal from 1 to 10,000 hours.');return}setData(d=>({...d,skills:[...d.skills,{id:crypto.randomUUID(),name,category:cleanText(skill.category,30),level:skill.level,color:['peach','lavender','mint'][d.skills.length%3],icon:'✨',goal}]}));setSkill({name:'',category:'Creative',level:'Beginner',goal:'5'});setModal('');notify('Your new skill is ready to grow.')}
 async function addPost(e){e.preventDefault();const text=cleanText(postText,500);if(text.length<3){notify('Write at least 3 characters before sharing.');return}let mediaUrl='',storagePath='';if(postFile){if(!cloudUser){notify('Photo uploads require a signed-in Firebase account.');return}try{setUploading(true);const uploaded=await uploadPostImage(cloudUser.user,postFile);mediaUrl=uploaded.url;storagePath=uploaded.path}catch(err){notify(err.message==='invalid-image'?'Choose a non-empty JPEG, PNG, WebP, or GIF under 10 MiB.':'Photo upload failed. Check Storage setup and your connection.');return}finally{setUploading(false)}}setData(d=>({...d,posts:[{id:crypto.randomUUID(),author:d.user.name,handle:d.user.username,avatar:initials(d.user.name),color:'peach',skill:'Personal growth',time:'Just now',createdAt:new Date().toISOString(),text,mediaUrl,storagePath,likes:0,liked:false,comments:[],mine:true},...d.posts]}));setPostText('');setPostFile(null);setModal('');setPage('Community');notify('Your update is out in the community!')}
 async function removePost(post){if(cloudUser){try{await deleteCloudPost(cloudUser.user,post)}catch{notify('Post could not be deleted.');return}}setData(d=>({...d,posts:d.posts.filter(p=>p.id!==post.id)}))}
 async function toggleLike(id){const post=data.posts.find(p=>p.id===id);if(!post)return;const liked=!post.liked;setData(d=>({...d,posts:d.posts.map(p=>p.id===id?{...p,liked,likes:Math.max(0,(Number(p.likes)||0)+(liked?1:-1))}:p)}));if(cloudUser){try{const count=await setCloudLike(cloudUser.user,id,liked);setData(d=>({...d,posts:d.posts.map(p=>p.id===id?{...p,liked,likes:count}:p)}))}catch{setData(d=>({...d,posts:d.posts.map(p=>p.id===id?{...p,liked:post.liked,likes:post.likes}:p)}));notify('Like could not be saved. Check your connection.')}}}
 async function addComment(e,post){e.preventDefault();const text=cleanText(commentDrafts[post.id],500);if(!text){notify('Write a comment first.');return}if(cloudUser){try{const comment=await addCloudComment(cloudUser.user,post.id,me.name,text);setData(d=>({...d,posts:d.posts.map(p=>p.id===post.id?{...p,comments:[...(p.comments||[]),comment]}:p)}))}catch{notify('Comment could not be saved. Check your connection.');return}}else setData(d=>({...d,posts:d.posts.map(p=>p.id===post.id?{...p,comments:[...(p.comments||[]),{id:crypto.randomUUID(),name:me.name,text,mine:true}]}:p)}));setCommentDrafts(d=>({...d,[post.id]:''}))}
 async function removeComment(post,comment){if(cloudUser&&comment.userId===cloudUser.user.uid){try{await deleteCloudComment(post.id,comment.id)}catch{notify('Comment could not be deleted.');return}}setData(d=>({...d,posts:d.posts.map(p=>p.id===post.id?{...p,comments:p.comments.filter(c=>c.id!==comment.id)}:p)}))}
 const filteredSkills=useMemo(()=>data.skills.filter(s=>s.name.toLowerCase().includes(query.toLowerCase())),[data.skills,query]);
 const week=Array.from({length:7},(_,i)=>{const day=new Date();day.setDate(day.getDate()-(6-i));const key=dateKey(day);return {label:['S','M','T','W','T','F','S'][day.getDay()],value:data.sessions.filter(s=>dateKey(s.practicedAt)===key).reduce((n,s)=>n+s.minutes,0)}});
 const weekMax=Math.max(60,...week.map(x=>x.value));
 return <div className="app-shell">
  <aside className={`sidebar ${mobileNav?'open':''}`}><a className="brand" onClick={()=>setPage('Home')}><span className="brand-mark"><Flower2 size={21}/></span><span>skillbloom<span className="brand-dot">.</span></span></a><div className="workspace"><Avatar name={me.name} color="peach" small/><span><b>Personal space</b><small>Free plan</small></span><ChevronDown size={15}/></div><span className="nav-label">WORKSPACE</span><nav>{nav.map(([label,Icon])=><button key={label} className={`nav-item ${page===label?'active':''}`} onClick={()=>{setPage(label);setMobileNav(false)}}><Icon size={18}/><span>{label}</span>{label==='Community'&&<span className="nav-count">2</span>}</button>)}</nav><div className="sidebar-bottom"><div className="streak-card"><div className="streak-icon"><Flame size={17}/></div><div><b>{streak} day streak</b><small>Keep your rhythm going</small></div><ChevronRight size={15}/></div><button className="nav-item"><CircleHelp size={18}/><span>Help & feedback</span></button><button className="nav-item" onClick={()=>setModal('settings')}><Settings2 size={18}/><span>Settings</span></button><div className="profile-row"><Avatar name={me.name}/><span><b>{me.name}</b><small>@{me.username}</small></span><button title="Sign out" onClick={()=>setModal('signout')}><LogOut size={17}/></button></div></div></aside>
  {mobileNav&&<div className="scrim" onClick={()=>setMobileNav(false)}/>}
  <main className="main"><header className="topbar"><button className="mobile-menu icon-button" onClick={()=>setMobileNav(true)}><Menu size={20}/></button><div className="crumb">Workspace <ChevronRight size={14}/> <strong>{page}</strong></div><div className="top-actions"><label className="search"><Search size={16}/><input placeholder="Search your skills..." value={query} onChange={e=>setQuery(e.target.value)}/><kbd>⌘ K</kbd></label><button className="icon-button bell" aria-label="Notifications" onClick={()=>notify('You’re all caught up!')}><Bell size={18}/><i/></button><Avatar name={me.name} color="peach" small/></div></header>{cloudError&&<div className="cloud-warning" role="status">{cloudError}</div>}
  {page==='Home'&&<div className="content"><div className="welcome-row"><div><div className="eyebrow"><Sparkles size={14}/> {new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'}).toUpperCase()}</div><h1>A little progress,<br/><em>every day.</em></h1><p className="welcome-sub">You’re building something good, {me.name.split(' ')[0]}.</p></div><button className="primary" onClick={()=>setModal('log')}><Plus size={17}/> Log practice</button></div>
   <section className="stats-grid"><Stat icon={Leaf} label="Active skills" value={data.skills.length} sub="Keep exploring" tone="green"/><Stat icon={Clock3} label="Practice time" value={`${(totalMinutes/60).toFixed(1)}h`} sub="Across all your skills" tone="blue"/><Stat icon={Flame} label="Day streak" value={streak} sub={streak?'You’re on a roll!':'Start a new rhythm'} tone="orange"/><Stat icon={Trophy} label="Goals reached" value={data.goals.filter(g=>progressPercent(goalCurrent(g),g.target)===100).length} sub={`${data.goals.length} goals in progress`} tone="purple"/></section>
   <section className="dashboard-grid"><div className="panel skills-panel"><div className="panel-head"><div><div className="eyebrow muted">YOUR JOURNEY</div><h2>Growing right now <span className="count-pill">{filteredSkills.length}</span></h2></div><button className="text-button" onClick={()=>setPage('My skills')}>All skills <ChevronRight size={15}/></button></div><div className="skill-list">{filteredSkills.slice(0,3).map(s=><SkillRow key={s.id} skill={s} minutes={skillWeekMinutes(s.id)} onClick={()=>setPage('My skills')}/>)}</div><button className="add-skill" onClick={()=>setModal('skill')}><span><Plus size={18}/></span><b>Add a skill to your journey</b><ChevronRight size={16}/></button></div>
    <div className="panel rhythm-panel"><div className="panel-head"><div><div className="eyebrow muted">YOUR CONSISTENCY</div><h2>Practice rhythm</h2></div><button className="select-mini">This week <ChevronDown size={13}/></button></div><div className="week-summary"><strong>{(week.reduce((a,b)=>a+b.value,0)/60).toFixed(1)}<small> hrs</small></strong><span><ArrowUpRight size={14}/> showing up is the win</span></div><div className="chart">{week.map((d,i)=><div key={i} className="chart-col"><div className="bar-track"><div className={`bar ${d.value?'filled':''}`} style={{height:`${Math.max(6,d.value/weekMax*100)}%`}}/></div><small>{d.label}</small></div>)}</div><div className="chart-note"><span className="legend-dot"/>Minutes practiced <span className="chart-note-right">Last 7 days</span></div></div></section>
   <section className="lower-grid"><div className="panel goals-panel"><div className="panel-head"><div><div className="eyebrow muted">ONE STEP AT A TIME</div><h2>Goals in motion</h2></div><button className="text-button" onClick={()=>setPage('Goals')}>View all <ChevronRight size={15}/></button></div>{data.goals.slice(0,2).map(g=>{const s=data.skills.find(x=>x.id===g.skillId);const current=goalCurrent(g);const pct=progressPercent(current,g.target);return <div className="goal-row" key={g.id}><div className="goal-icon">{s?.icon||'🎯'}</div><div className="goal-info"><div className="goal-title"><b>{g.title}</b><span>{pct}%</span></div><div className="progress-track"><div style={{width:`${pct}%`}}/></div><small>{current.toFixed(1)} of {g.target} {g.unit} · {s?.name||'Skill'}</small></div></div>})}{!data.goals.length&&<Empty text="Set a small, meaningful goal to begin."/>}</div>
    <div className="panel activity-panel"><div className="panel-head"><div><div className="eyebrow muted">FRESH FROM YOUR PRACTICE</div><h2>Recent activity</h2></div><button className="text-button" onClick={()=>setPage('Practice log')}>See log <ChevronRight size={15}/></button></div>{data.sessions.slice(0,3).map(s=>{const sk=data.skills.find(x=>x.id===s.skillId);return <div className="activity-row" key={s.id}><div className={`activity-dot ${sk?.color||'mint'}`}>{sk?.icon||'✨'}</div><div><b>{s.activity}</b><small>{sk?.name||'Skill'} · {new Date(s.practicedAt).toLocaleDateString(undefined,{month:'short',day:'numeric'})}</small></div><span>{s.minutes}m</span></div>})}{!data.sessions.length&&<Empty text="Your practice sessions will show up here."/>}</div></section>
   <section className="community-banner"><div className="banner-art"><span>✿</span><span>✧</span><span>❋</span></div><div><div className="eyebrow">GROWING IS BETTER TOGETHER</div><h2>Celebrate the small wins.</h2><p>Share what you’re learning and cheer on your community.</p></div><button className="secondary" onClick={()=>setPage('Community')}>Visit community <ArrowUpRight size={16}/></button></section>
  </div>}
  {page==='My skills'&&<div className="content page-content"><PageTitle eyebrow="YOUR PERSONAL GARDEN" title="My skills" sub="Every skill grows at its own pace." action={<button className="primary" onClick={()=>setModal('skill')}><Plus size={17}/> Add skill</button>}/><div className="skill-cards">{filteredSkills.map(s=><SkillCard key={s.id} skill={s} minutes={skillWeekMinutes(s.id)} sessions={data.sessions.filter(x=>x.skillId===s.id).length} onDelete={()=>setData(d=>({...d,skills:d.skills.filter(x=>x.id!==s.id),sessions:d.sessions.filter(x=>x.skillId!==s.id),goals:d.goals.filter(x=>x.skillId!==s.id)}))}/>)}</div>{!filteredSkills.length&&<Empty text="No skills match that search yet."/>}</div>}
  {page==='Practice log'&&<div className="content page-content"><PageTitle eyebrow="SHOW UP FOR YOURSELF" title="Practice log" sub="A record of every little step." action={<button className="primary" onClick={()=>setModal('log')}><Plus size={17}/> Log practice</button>}/><div className="panel log-panel"><div className="panel-head"><h2>All sessions <span className="count-pill">{data.sessions.length}</span></h2><span className="muted-caption">{(totalMinutes/60).toFixed(1)} hours total</span></div>{data.sessions.map(s=>{const sk=data.skills.find(x=>x.id===s.skillId);return <div className="log-row" key={s.id}><div className={`activity-dot ${sk?.color||'mint'}`}>{sk?.icon||'✨'}</div><div className="log-main"><b>{s.activity}</b><small>{sk?.name||'Skill'} · {new Date(s.practicedAt).toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'})}</small></div><strong>{s.minutes} min</strong><button className="icon-button delete" title="Delete session" onClick={()=>setData(d=>({...d,sessions:d.sessions.filter(x=>x.id!==s.id)}))}><X size={16}/></button></div>})}{!data.sessions.length&&<Empty text="Your first session is just one small step away."/>}</div></div>}
  {page==='Goals'&&<div className="content page-content"><PageTitle eyebrow="AIM FOR SOMETHING MEANINGFUL" title="Goals & milestones" sub="Make your next step feel possible." action={<button className="primary" onClick={()=>setModal('goal')}><Plus size={17}/> New goal</button>}/><div className="goal-cards">{data.goals.map(g=>{const sk=data.skills.find(s=>s.id===g.skillId);const current=goalCurrent(g);const pct=progressPercent(current,g.target);return <div className="panel goal-card" key={g.id}><div className="goal-card-top"><div className="goal-icon large">{sk?.icon||'🎯'}</div><span className="status-pill">{pct===100?'Completed':'In progress'}</span></div><h2>{g.title}</h2><p>{sk?.name||'Skill'} · target {g.target} {g.unit}</p><div className="progress-track thick"><div style={{width:`${pct}%`}}/></div><div className="goal-card-foot"><span>{current.toFixed(1)} {g.unit} completed</span><b>{pct}%</b></div><small>Target date · {new Date(g.deadline+'T12:00:00').toLocaleDateString(undefined,{month:'long',day:'numeric',year:'numeric'})}</small></div>})}{!data.goals.length&&<Empty text="Goals help turn a wish into a plan."/>}</div></div>}
  {page==='Community'&&<div className="content page-content"><PageTitle eyebrow="A KINDER CORNER OF THE INTERNET" title="Community" sub="A little encouragement goes a long way." action={<button className="primary" onClick={()=>setModal('post')}><Plus size={17}/> Share an update</button>}/><div className="community-layout"><div className="feed">{data.posts.map(p=><article className="panel post-card" key={p.id}><div className="post-head"><Avatar name={p.author} color={p.color}/><div><b>{p.author}</b><small>@{p.handle} · {p.time}</small></div><button className="icon-button post-more" aria-label="More post options" onClick={()=>p.mine?removePost(p):notify('Thanks for helping keep the community kind.')}><MoreHorizontal size={20}/></button></div><div className="post-tag"><Sparkles size={12}/>{p.skill}</div><p className="post-text">{p.text}</p>{p.mediaUrl&&<img className="post-image" src={p.mediaUrl} alt="Attachment shared with this learning update" loading="lazy"/>}<div className="post-actions"><button className={p.liked?'liked':''} onClick={()=>toggleLike(p.id)}><Heart size={17} fill={p.liked?'currentColor':'none'}/>{Number(p.likes)||0} likes</button><button onClick={()=>setOpenComments(c=>({...c,[p.id]:!c[p.id]}))}><MessageCircle size={17}/>{p.comments?.length||0} comments</button><span>{p.mine?'Your update':'Community'}</span></div>{openComments[p.id]&&<div className="comment-area">{p.comments?.map(c=><div className="comment-row" key={c.id}><Avatar name={c.name||c.author||'Learner'} small/><div><b>{c.name||c.author||'Learner'}</b><p>{c.text||c.content}</p></div>{(c.mine||c.userId===cloudUser?.user.uid)&&<button className="comment-delete" onClick={()=>removeComment(p,c)} aria-label="Delete your comment">×</button>}</div>)}<form className="comment-form" onSubmit={e=>addComment(e,p)}><input maxLength="500" value={commentDrafts[p.id]||''} onChange={e=>setCommentDrafts(d=>({...d,[p.id]:e.target.value}))} placeholder="Write a kind comment…"/><button type="submit">Send</button></form></div>}</article>)}{!data.posts.length&&<Empty text="Be the first to share a learning moment."/>}</div><aside className="community-aside"><div className="panel aside-card"><div className="aside-flower">✿</div><h3>Growing together</h3><p>Every expert was once a beginner. Show up, share a little, encourage someone else.</p><button className="secondary full" onClick={()=>setModal('post')}><Plus size={16}/> Share a small win</button></div><div className="panel aside-card prompt-card"><span className="eyebrow muted">A PROMPT FOR YOU</span><h3>What felt a little easier this week?</h3><button className="text-button" onClick={()=>{setPostText('This week, ');setModal('post')}}>Write about it <ChevronRight size={15}/></button></div></aside></div></div>}
  <footer className="footer">Made for the things you love <span>✿</span><a>Privacy</a><a>About</a></footer></main>
  {modal&&<Modal title={modal==='log'?'Log a practice session':modal==='skill'?'Plant a new skill':modal==='goal'?'Set a goal':modal==='post'?'Share a small win':modal==='settings'?'Your profile':'Sign out'} close={()=>setModal('')}>
   {modal==='log'&&<form onSubmit={addSession} className="form"><label>Skill<select value={session.skillId} onChange={e=>setSession({...session,skillId:e.target.value})}>{data.skills.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label><label>What did you work on?<input autoFocus maxLength="100" value={session.activity} onChange={e=>setSession({...session,activity:e.target.value})} placeholder="e.g. Practiced chord transitions" required/></label><div className="form-split"><label>Minutes<input type="number" min="1" max="1440" value={session.minutes} onChange={e=>setSession({...session,minutes:e.target.value})} required/></label><label>Date<input type="date" max={dateKey(new Date())} value={session.practicedAt} onChange={e=>setSession({...session,practicedAt:e.target.value})} required/></label></div><button className="primary full" type="submit"><Check size={17}/> Save session</button></form>}
   {modal==='skill'&&<form onSubmit={addSkill} className="form"><label>Skill name<input autoFocus maxLength="48" value={skill.name} onChange={e=>setSkill({...skill,name:e.target.value})} placeholder="e.g. Pottery" required/></label><label>Category<input maxLength="30" value={skill.category} onChange={e=>setSkill({...skill,category:e.target.value})}/></label><div className="form-split"><label>Current level<select value={skill.level} onChange={e=>setSkill({...skill,level:e.target.value})}><option>Beginner</option><option>Intermediate</option><option>Advanced</option></select></label><label>Weekly target (hours)<input type="number" min="1" max="10000" value={skill.goal} onChange={e=>setSkill({...skill,goal:e.target.value})}/></label></div><button className="primary full" type="submit"><Leaf size={17}/> Add to my skills</button></form>}
   {modal==='goal'&&<GoalForm skills={data.skills} onSave={g=>{setData(d=>({...d,goals:[...d.goals,g]}));setModal('');notify('A new goal is taking shape.')}}/>}
   {modal==='post'&&<form onSubmit={addPost} className="form"><div className="compose-user"><Avatar name={me.name}/><div><b>{me.name}</b><small>Sharing with the community</small></div></div><label className="sr-only" htmlFor="post-text">Your update</label><textarea id="post-text" autoFocus rows="5" maxLength="500" value={postText} onChange={e=>setPostText(e.target.value)} placeholder="What have you been learning lately?"/><div className="upload-row"><label className={`upload-control ${!cloudUser?'disabled':''}`}><ImagePlus size={16}/> Add a photo{cloudUser&&<input type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={e=>setPostFile(e.target.files?.[0]||null)}/>}</label>{postFile&&<span className="upload-name">{postFile.name.slice(0,28)} <button type="button" onClick={()=>setPostFile(null)} aria-label="Remove photo">×</button></span>}</div><div className="form-foot"><small>{postText.length}/500 · Be kind, be you.</small><button className="primary" type="submit" disabled={uploading}>{uploading?'Uploading photo…':<>Share update <ArrowUpRight size={16}/></>}</button></div></form>}
   {modal==='settings'&&<ProfileForm user={me} onSave={x=>{setUser(x);setModal('');notify('Profile updated.')}}/>}
   {modal==='signout'&&<div className="form"><p>{cloudUser?'Sign out of your Skillbloom account? Your cloud data will stay in your account.':'Local demo data stays in this browser. Clear it to start fresh?'}</p>{cloudUser?<button className="danger-button full" onClick={async()=>{setModal('');await cloudUser.logout()}}>Sign out</button>:<button className="danger-button full" onClick={()=>{localStorage.removeItem(STORE);setData(starter);setModal('');notify('Demo data reset.')}}>Reset demo data</button>}<button className="secondary full" onClick={()=>setModal('')}>Cancel</button></div>}
  </Modal>}
  {toast&&<div className="toast"><Check size={16}/>{toast}</div>}
 </div>
}
function Stat({icon:Icon,label,value,sub,tone}){return <div className="panel stat-card"><div className={`stat-icon ${tone}`}><Icon size={18}/></div><span className="stat-label">{label}</span><strong>{value}</strong><small>{sub}</small></div>}
function SkillRow({skill,minutes,onClick}){const pct=progressPercent(minutes,skill.goal*60);return <button className="skill-row" onClick={onClick}><div className={`skill-emoji ${skill.color}`}>{skill.icon}</div><div className="skill-main"><div className="skill-title"><b>{skill.name}</b><span>{skill.level}</span></div><small>{skill.category} · {(minutes/60).toFixed(1)} / {skill.goal} hrs</small><div className="progress-track"><div style={{width:`${pct}%`}}/></div></div><ChevronRight size={17}/></button>}
function SkillCard({skill,minutes,sessions,onDelete}){const pct=progressPercent(minutes,skill.goal*60);return <article className="panel skill-card"><div className="skill-card-top"><div className={`skill-emoji big ${skill.color}`}>{skill.icon}</div><button className="icon-button" title="Remove skill" onClick={onDelete}><MoreHorizontal size={20}/></button></div><span className="skill-category">{skill.category}</span><h2>{skill.name}</h2><span className="level-pill">{skill.level}</span><div className="skill-card-progress"><div className="goal-title"><span>Weekly practice</span><b>{pct}%</b></div><div className="progress-track thick"><div style={{width:`${pct}%`}}/></div><small>{(minutes/60).toFixed(1)} / {skill.goal} hours · {sessions} sessions</small></div></article>}
function Empty({text}){return <div className="empty"><span>✿</span><p>{text}</p></div>}
function PageTitle({eyebrow,title,sub,action}){return <div className="page-title"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{sub}</p></div>{action}</div>}
function Modal({title,close,children}){return <div className="modal-overlay" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="modal"><div className="modal-head"><h2>{title}</h2><button className="icon-button" onClick={close} aria-label="Close"><X size={19}/></button></div>{children}</div></div>}
function GoalForm({skills,onSave}){const [f,setF]=useState({skillId:skills[0]?.id||'',title:'',target:'5',unit:'hours',deadline:''});return <form className="form" onSubmit={e=>{e.preventDefault();if(!cleanText(f.title,80)){return}onSave({...f,id:crypto.randomUUID(),title:cleanText(f.title,80),target:Number(f.target),deadline:f.deadline,status:'In progress'})}}><label>Related skill<select value={f.skillId} onChange={e=>setF({...f,skillId:e.target.value})}>{skills.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Goal<input autoFocus maxLength="80" required placeholder="e.g. Complete my first painting" value={f.title} onChange={e=>setF({...f,title:e.target.value})}/></label><div className="form-split"><label>Target value<input required type="number" min="1" max="10000" value={f.target} onChange={e=>setF({...f,target:e.target.value})}/></label><label>Unit<select value={f.unit} onChange={e=>setF({...f,unit:e.target.value})}><option>hours</option><option>sessions</option></select></label></div><label>Target date<input type="date" required min={dateKey(new Date())} value={f.deadline} onChange={e=>setF({...f,deadline:e.target.value})}/></label><button className="primary full" type="submit"><Target size={17}/> Create goal</button></form>}
function ProfileForm({user,onSave}){const [f,setF]=useState(user);return <form className="form" onSubmit={e=>{e.preventDefault();onSave({...f,name:cleanText(f.name,60),username:cleanText(f.username,24).replace(/^@/,''),bio:cleanText(f.bio,160)})}}><label>Your name<input required maxLength="60" value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></label><label>Username<input required maxLength="24" value={f.username} onChange={e=>setF({...f,username:e.target.value.replace(/[^a-zA-Z0-9_]/g,'')})}/></label><label>Bio<textarea rows="3" maxLength="160" value={f.bio} onChange={e=>setF({...f,bio:e.target.value})}/></label><button className="primary full" type="submit"><Check size={17}/> Save profile</button></form>}
