import React,{useEffect,useState} from 'react';
import {BookOpen,Eye,EyeOff,Flower2,Leaf,LockKeyhole,Mail,ShieldCheck,Sparkles} from 'lucide-react';
import App from './App.jsx';
import {firebaseReady,watchAuth,login,register,resetPassword,loadCloudData,saveCloudData,logout} from './firebase.js';
import {cleanText,validEmail,validPassword} from './logic.js';

export default function AuthGate(){
 const [user,setUser]=useState(null),[initialData,setInitialData]=useState(null),[loading,setLoading]=useState(firebaseReady),[demo,setDemo]=useState(!firebaseReady),[cloudError,setCloudError]=useState('');
 useEffect(()=>{if(!firebaseReady)return;return watchAuth(async account=>{setUser(account);if(account){setLoading(true);setCloudError('');try{setInitialData(await loadCloudData(account))}catch{setCloudError('We could not load your cloud data. Check your connection and Firestore rules.');setInitialData({user:{name:account.displayName||'Learner',email:account.email||'',username:'learner',bio:''},skills:[],sessions:[],goals:[],posts:[]})}finally{setLoading(false)}}else{setInitialData(null);setLoading(false)}})},[]);
 if(demo||!firebaseReady)return <App/>;
 if(loading)return <div className="auth-page"><div className="auth-loading"><Flower2 size={26}/><p>Getting your garden ready…</p></div></div>;
 if(user&&initialData)return <App key={user.uid} cloudUser={{user,data:initialData,logout}} cloudError={cloudError}/>;
 return <AuthPanel onDemo={()=>setDemo(true)}/>;
}
function AuthPanel({onDemo}){
 const[mode,setMode]=useState('login'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[showPass,setShowPass]=useState(false);
 async function submit(e){e.preventDefault();setError('');setNotice('');const em=email.trim().normalize('NFKC');if(!validEmail(em)){setError('Enter a valid email address.');return}if(mode==='reset'){setBusy(true);try{await resetPassword(em);setNotice('If an account uses that address, a reset link has been sent.')}catch{setNotice('If an account uses that address, a reset link has been sent.')}finally{setBusy(false)}return}if(mode==='signup'&&!validPassword(password)){setError('Use 10–128 characters with uppercase, lowercase, and a number.')}else if(password.length<1||password.length>128){setError('Enter a password between 1 and 128 characters.')}else if(mode==='signup'&&cleanText(name,60).length<2){setError('Your name must contain at least 2 characters.')}else{setBusy(true);try{if(mode==='signup')await register(em,password,cleanText(name,60));else await login(em,password)}catch(err){const code=err?.code||'';setError(code.includes('too-many-requests')?'Too many attempts. Wait a moment and try again.':code.includes('network-request-failed')?'Network unavailable. Check your connection and try again.':mode==='signup'&&code.includes('email-already-in-use')?'That email is already registered. Try signing in.':mode==='signup'&&code.includes('weak-password')?'Choose a stronger password (at least 10 characters).':'Email or password could not be verified. Check your details and try again.')}finally{setBusy(false)}}}
 return <div className="auth-page"><div className="auth-card"><div className="auth-brand"><span className="brand-mark"><Flower2 size={22}/></span><span>skillbloom<span className="brand-dot">.</span></span></div><div className="auth-illustration"><div className="auth-sun"/><div className="auth-leaf"><Leaf size={37}/></div><span>✧</span><i>✿</i></div><div className="auth-copy"><div className="eyebrow">A LITTLE PROGRESS, EVERY DAY</div><h1>{mode==='signup'?'Make room to grow.':mode==='reset'?'A fresh start.':'Welcome back.'}</h1><p>{mode==='signup'?'Create your account and start growing the skills you love.':mode==='reset'?'We’ll send a reset link if there’s an account for that email.':'Your next small step is waiting.'}</p></div><form className="auth-form" onSubmit={submit}>{mode==='signup'&&<label>Your name<input autoComplete="name" maxLength="60" value={name} onChange={e=>setName(e.target.value)} placeholder="Your name"/></label>}<label>Email address<div className="auth-input"><Mail size={16}/><input type="email" autoComplete="email" maxLength="254" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" required/></div></label>{mode!=='reset'&&<label>Password<div className="auth-input"><LockKeyhole size={16}/><input type={showPass?'text':'password'} autoComplete={mode==='signup'?'new-password':'current-password'} maxLength="128" value={password} onChange={e=>setPassword(e.target.value)} placeholder={mode==='signup'?'10+ characters, mixed case and a number':'Your password'} required/><button type="button" onClick={()=>setShowPass(!showPass)} aria-label={showPass?'Hide password':'Show password'}>{showPass?<EyeOff size={16}/>:<Eye size={16}/>}</button></div></label>}{error&&<div className="auth-error" role="alert">{error}</div>}{notice&&<div className="auth-notice" role="status">{notice}</div>}{mode==='login'&&<button type="button" className="auth-link forgot" onClick={()=>{setMode('reset');setError('');setNotice('')}}>Forgot password?</button>}<button className="primary full auth-submit" disabled={busy} type="submit">{busy?'Please wait…':mode==='signup'?'Create account':mode==='reset'?'Send reset link':'Sign in'}</button></form><div className="auth-switch">{mode==='login'?<>New to Skillbloom? <button onClick={()=>{setMode('signup');setError('')}}>Create an account</button></>:<>Already have an account? <button onClick={()=>{setMode('login');setError('')}}>Sign in</button></>}</div><div className="auth-secure"><ShieldCheck size={14}/> Your account is secured with Firebase Authentication</div><button className="auth-demo" onClick={onDemo}><BookOpen size={15}/> Explore the local demo instead</button></div><div className="auth-side-note"><Sparkles size={15}/> Your progress belongs to you.</div></div>
}
