import { initializeApp, getApps } from 'firebase/app';
import { getAuth, onAuthStateChanged, createUserWithEmailAndPassword, signInWithEmailAndPassword, sendPasswordResetEmail, signOut, updateProfile } from 'firebase/auth';
import { getFirestore, doc, getDoc, setDoc, deleteDoc, collection, getDocs, writeBatch, serverTimestamp, query, orderBy, limit } from 'firebase/firestore';
import { getStorage, ref, uploadBytes, getDownloadURL, deleteObject } from 'firebase/storage';

const config={apiKey:import.meta.env.VITE_FIREBASE_API_KEY,authDomain:import.meta.env.VITE_FIREBASE_AUTH_DOMAIN,projectId:import.meta.env.VITE_FIREBASE_PROJECT_ID,storageBucket:import.meta.env.VITE_FIREBASE_STORAGE_BUCKET,messagingSenderId:import.meta.env.VITE_FIREBASE_MESSAGING_SENDER_ID,appId:import.meta.env.VITE_FIREBASE_APP_ID};
export const firebaseReady=Boolean(config.apiKey&&config.authDomain&&config.projectId&&config.appId);
const app=firebaseReady?(getApps()[0]||initializeApp(config)):null;
export const auth=app?getAuth(app):null;
const db=app?getFirestore(app):null;
const storage=app&&config.storageBucket?getStorage(app):null;
export const watchAuth=callback=>auth?onAuthStateChanged(auth,callback):()=>{};
export async function register(email,password,name){const credential=await createUserWithEmailAndPassword(auth,email,password);const displayName=name.trim();if(displayName)await updateProfile(credential.user,{displayName});await setDoc(doc(db,'users',credential.user.uid),{name:displayName,email:credential.user.email,username:displayName.toLowerCase().replace(/[^a-z0-9]+/g,'').slice(0,24)||'learner',bio:'',createdAt:serverTimestamp()});return credential.user;}
export async function login(email,password){return (await signInWithEmailAndPassword(auth,email,password)).user;}
export async function resetPassword(email){return sendPasswordResetEmail(auth,email);}
export async function logout(){if(auth)await signOut(auth);}
export async function uploadPostImage(user,file){if(!storage)throw new Error('storage-not-configured');if(!file||!['image/jpeg','image/png','image/webp','image/gif'].includes(file.type)||file.size<1||file.size>=10*1024*1024)throw new Error('invalid-image');const object=ref(storage,`users/${user.uid}/posts/${crypto.randomUUID()}`);await uploadBytes(object,file,{contentType:file.type});return {url:await getDownloadURL(object),path:object.fullPath};}
export async function deleteCloudPost(user,post){await deleteDoc(doc(db,'posts',post.id));if(storage&&typeof post.storagePath==='string'&&post.storagePath.startsWith(`users/${user.uid}/posts/`)){await deleteObject(ref(storage,post.storagePath)).catch(()=>{})}}
const privateCollections=['skills','sessions','goals'];
export async function loadCloudData(user){const base=doc(db,'users',user.uid);const [profile,...groups]=await Promise.all([getDoc(base),...privateCollections.map(name=>getDocs(collection(db,'users',user.uid,name))),getDocs(query(collection(db,'posts'),orderBy('createdAt','desc'),limit(50)))]);const d=profile.exists()?profile.data():{};const posts=await Promise.all(groups[3].docs.map(async x=>{const [likes,comments]=await Promise.all([getDocs(collection(db,'posts',x.id,'likes')),getDocs(query(collection(db,'posts',x.id,'comments'),orderBy('createdAt','asc')))]);return {id:x.id,...x.data(),likes:likes.size,liked:likes.docs.some(l=>l.id===user.uid),comments:comments.docs.map(c=>({id:c.id,...c.data(),mine:c.data().userId===user.uid})),mine:x.data().userId===user.uid}}));return {user:{name:d.name||user.displayName||'Learner',email:user.email||'',username:d.username||'learner',bio:d.bio||''},skills:groups[0].docs.map(x=>({id:x.id,...x.data()})),sessions:groups[1].docs.map(x=>({id:x.id,...x.data()})),goals:groups[2].docs.map(x=>({id:x.id,...x.data()})),posts};}
export async function setCloudLike(user,postId,liked){const ref=doc(db,'posts',postId,'likes',user.uid);if(liked)await setDoc(ref,{userId:user.uid,createdAt:serverTimestamp()});else await deleteDoc(ref);const likes=await getDocs(collection(db,'posts',postId,'likes'));return likes.size;}
export async function addCloudComment(user,postId,name,text){const id=crypto.randomUUID();const comment={id,userId:user.uid,name,text,createdAt:serverTimestamp()};await setDoc(doc(db,'posts',postId,'comments',id),comment);return {...comment,createdAt:new Date().toISOString()};}
export async function deleteCloudComment(postId,commentId){await deleteDoc(doc(db,'posts',postId,'comments',commentId));}
export async function saveCloudData(user,data){const base=doc(db,'users',user.uid);await setDoc(base,{...data.user,email:user.email||'',updatedAt:serverTimestamp()},{merge:true});await Promise.all(privateCollections.map(async name=>{const rows=Array.isArray(data[name])?data[name]:[];const ref=collection(db,'users',user.uid,name);const old=await getDocs(ref);const byId=new Map(rows.filter(x=>x&&typeof x.id==='string').map(x=>[x.id,x]));const changed=[...old.docs.filter(s=>!byId.has(s.id)).map(s=>({type:'delete',ref:s.ref})),...byId].map(x=>Array.isArray(x)?({type:'set',ref:doc(ref,x[0]),payload:Object.fromEntries(Object.entries(x[1]).filter(([k])=>k!=='id'))}):x);for(let i=0;i<changed.length;i+=450){const batch=writeBatch(db);changed.slice(i,i+450).forEach(op=>op.type==='delete'?batch.delete(op.ref):batch.set(op.ref,op.payload));await batch.commit()}}));const ownPosts=data.posts.filter(p=>p.mine||p.userId===user.uid);for(let i=0;i<ownPosts.length;i+=450){const batch=writeBatch(db);ownPosts.slice(i,i+450).forEach(p=>{const {id,liked,likes,comments,mine,...payload}=p;batch.set(doc(db,'posts',id),{...payload,userId:user.uid,createdAt:payload.createdAt||serverTimestamp()},{merge:true})});await batch.commit()}}
